"""Adicionando coluna dono com FK nomeada

Revision ID: ec56e263f8ce
Revises: 
Create Date: 2025-07-24 13:14:05.075081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec56e263f8ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userName', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userName')
    )
    op.create_table('fichas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dono', sa.Integer(), nullable=False),
    sa.Column('personagem', sa.String(length=80), nullable=False),
    sa.Column('classe', sa.String(length=80), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('raca', sa.String(length=80), nullable=False),
    sa.Column('forca', sa.Integer(), nullable=False),
    sa.Column('destreza', sa.Integer(), nullable=False),
    sa.Column('constituicao', sa.Integer(), nullable=False),
    sa.Column('inteligencia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dono'], ['usuarios.id'], name='fk_fichas_dono'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fichas')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
